INSERT INTO Tasks (task_name, task_description, task_due_date, task_priority, status) VALUES
    ('Complete Project Proposal', 'Write and finalize the project proposal document.', '2024-05-20', 1, 1),
    ('Prepare Presentation Slides', 'Create slides for the upcoming presentation.', '2024-05-25', 2, 1),
    ('Research Topic', 'Gather information and resources for the research topic.', '2024-05-18', 3, 1),
    ('Code Refactoring', 'Review and refactor existing codebase for optimization.', '2024-05-22', 2, 1),
    ('Meeting with Client', 'Discuss project progress and gather feedback from the client.', '2024-05-27', 1, 1),
    ('Write Test Cases', 'Develop test cases to ensure software reliability.', '2024-05-21', 2, 1),
    ('Update Documentation', 'Revise and update project documentation.', '2024-05-23', 3, 1),
    ('Data Analysis', 'Analyze collected data to identify patterns and trends.', '2024-05-19', 1, 1),
    ('Training Session', 'Conduct training session for team members on new technologies.', '2024-05-26', 2, 1),
    ('Bug Fixing', 'Identify and fix bugs reported during testing phase.', '2024-05-24', 1, 1),
    ('Client Meeting Preparation', 'Prepare agenda and materials for upcoming client meeting.', '2024-05-28', 2, 1),
    ('Database Optimization', 'Optimize database queries for improved performance.', '2024-05-29', 3, 1),
    ('Content Creation', 'Create content for marketing campaign.', '2024-05-30', 1, 1),
    ('Security Audit', 'Conduct security audit to identify vulnerabilities.', '2024-05-31', 2, 1),
    ('Performance Testing', 'Perform load and stress testing on the application.', '2024-06-01', 3, 1),
    ('Review Code Changes', 'Review recent code changes for quality assurance.', '2024-06-05', 2, 1),
    ('Project Status Report', 'Prepare a status report on the progress of the project.', '2024-06-10', 1, 1),
    ('User Training', 'Organize training sessions for new software features.', '2024-06-15', 2, 1),
    ('Data Migration', 'Migrate data to the new database schema.', '2024-06-20', 3, 1),
    ('Documentation Update', 'Update user manuals and documentation.', '2024-06-25', 1, 1),
    ('System Integration Testing', 'Perform integration testing with external systems.', '2024-06-30', 2, 1),
    ('Code Review Meeting', 'Conduct a meeting to review recent code changes.', '2024-07-05', 3, 1),
    ('Infrastructure Upgrade', 'Upgrade server infrastructure for improved performance.', '2024-07-10', 1, 1),
    ('Customer Support Training', 'Provide training for customer support staff on new product features.', '2024-07-15', 2, 1),
    ('Marketing Campaign Planning', 'Plan upcoming marketing campaigns.', '2024-07-20', 3, 1),
    ('Feature Enhancement Development', 'Develop enhancements for existing product features.', '2024-07-25', 1, 1),
    ('Budget Review', 'Review project budget and expenses.', '2024-07-30', 2, 1),
    ('System Monitoring Setup', 'Set up monitoring tools for system health monitoring.', '2024-08-05', 3, 1),
    ('Quality Assurance Testing', 'Conduct comprehensive testing to ensure product quality.', '2024-08-10', 1, 1),
    ('Client Demo Preparation', 'Prepare demo materials for upcoming client presentations.', '2024-08-15', 2, 1),
    ('Client Demo Preparation', 'Prepare demo materials for upcoming client presentations.', '2024-08-15', 2, 1),
    ('Database Backup Configuration', 'Configure automated backups for database.', '2024-08-20', 3, 1),
    ('User Feedback Collection', 'Collect feedback from users for product improvement.', '2024-08-25', 1, 1),
    ('Application Performance Optimization', 'Optimize application performance for better user experience.', '2024-08-30', 2, 1),
    ('Training Material Development', 'Develop training materials for new employee orientation.', '2024-09-05', 3, 1),
    ('Market Research', 'Conduct market research for product positioning.', '2024-09-10', 1, 1),
    ('Project Planning Meeting', 'Conduct a meeting to plan upcoming project tasks.', '2024-09-15', 2, 1),
    ('System Maintenance', 'Perform routine maintenance tasks on server infrastructure.', '2024-09-20', 3, 1),
    ('Product Roadmap Review', 'Review and update product roadmap for future development.', '2024-09-25', 1, 1),
    ('Content Localization', 'Localize content for international markets.', '2024-09-30', 2, 1),
    ('Employee Performance Evaluation', 'Conduct performance evaluations for team members.', '2024-10-05', 3, 1),
    ('Release Management', 'Manage software release process and versioning.', '2024-10-10', 1, 1),
    ('Risk Assessment', 'Conduct risk assessment for potential project risks.', '2024-10-15', 2, 1),
    ('Vendor Evaluation', 'Evaluate potential vendors for project requirements.', '2024-10-20', 3, 1),
    ('Content Marketing Strategy', 'Develop content marketing strategy for product promotion.', '2024-10-25', 1, 1),
    ('Customer Satisfaction Survey', 'Conduct survey to measure customer satisfaction.', '2024-10-30', 2, 1),
    ('Customer Satisfaction Survey', 'Conduct survey to measure customer satisfaction.', '2024-10-30', 2, 1),
    ('Social Media Marketing', 'Develop social media marketing campaigns.', '2024-11-05', 3, 1),
    ('Server Migration', 'Migrate servers to a new hosting provider.', '2024-11-10', 1, 1),
    ('Competitor Analysis', 'Conduct analysis of competitors in the market.', '2024-11-15', 2, 1),
    ('Product Feature Prioritization', 'Prioritize product features for development.', '2024-11-20', 3, 1),
    ('Project Review Meeting', 'Review project progress and plan next steps.', '2024-09-10', 1, 1),
    ('Team Building Activity', 'Organize team building activity for morale boosting.', '2024-09-15', 2, 1),
    ('Software License Audit', 'Conduct audit of software licenses for compliance.', '2024-09-20', 3, 1),
    ('Financial Report Preparation', 'Prepare financial report for project stakeholders.', '2024-09-25', 1, 1),
    ('Content Management System Upgrade', 'Upgrade content management system to the latest version.', '2024-09-30', 2, 1),
    ('Product Demo Video Creation', 'Create demo videos for product demonstration.', '2024-10-05', 3, 1),
    ('Employee Training Session', 'Organize training session for employees on new tools.', '2024-10-10', 1, 1),
    ('Product Packaging Design', 'Design packaging for physical product distribution.', '2024-10-15', 2, 1),
    ('Website Security Audit', 'Conduct security audit of the company website.', '2024-10-20', 3, 1),
    ('Sales Forecast Analysis', 'Analyze sales data for forecasting future sales.', '2024-10-25', 1, 1),
    ('Project Documentation Review', 'Review and update project documentation.', '2024-10-30', 2, 1);
   

    
INSERT INTO Members (member_name, member_email) VALUES
    ('John Doe', 'john@example.com'),
    ('Jane Smith', 'jane@example.com'),
    ('Michael Johnson', 'michael@example.com'),
    ('Emily Brown', 'emily@example.com'),
    ('Christopher Wilson', 'christopher@example.com'),
    ('Jessica Lee', 'jessica@example.com'),
    ('Matthew Taylor', 'matthew@example.com'),
    ('Emma Martinez', 'emma@example.com'),
    ('Daniel Anderson', 'daniel@example.com'),
    ('Olivia Thomas', 'olivia@example.com'),
    ('William Garcia', 'william@example.com'),
    ('Ava Rodriguez', 'ava@example.com'),
    ('James Martinez', 'james@example.com'),
    ('Sophia Hernandez', 'sophia@example.com'),
    ('Alexander Smith', 'alexander@example.com'),
    ('Samantha Johnson', 'samantha@example.com'),
    ('Kevin Brown', 'kevin@example.com'),
    ('Madison Martinez', 'madison@example.com'),
    ('Carter Thompson', 'carter@example.com'),
    ('Victoria Garcia', 'victoria@example.com'),
    ('Dylan Robinson', 'dylan@example.com'),
    ('Zoe White', 'zoe@example.com'),
    ('Nathan Hall', 'nathan@example.com'),
    ('Brooklyn Young', 'brooklyn@example.com'),
    ('Jordan Hernandez', 'jordan@example.com'),
    ('Leah King', 'leah@example.com'),
    ('Brandon Adams', 'brandon@example.com'),
    ('Alyssa Hill', 'alyssa@example.com'),
    ('Gabriel Martinez', 'gabriel@example.com'),
    ('Hailey Turner', 'hailey@example.com'),
    ('Connor Harris', 'connor@example.com'),
    ('Evelyn Scott', 'evelyn@example.com'),
    ('Caleb Green', 'caleb@example.com'),
    ('Allison Baker', 'allison@example.com'),
    ('Isaac Gonzalez', 'isaac@example.com'),
    ('Makayla Nelson', 'makayla@example.com'),
    ('Justin Carter', 'justin@example.com'),
    ('Hannah Mitchell', 'hannah@example.com'),
    ('Elijah Perez', 'elijah@example.com'),
    ('Sophie Torres', 'sophie@example.com'),
    ('Landon Flores', 'landon@example.com'),
    ('Lily Morgan', 'lily@example.com'),
    ('Adrian Cooper', 'adrian@example.com'),
    ('Maya Reed', 'maya@example.com'),
    ('Gavin Richardson', 'gavin@example.com'),
    ('Natalie Wood', 'natalie@example.com'),
    ('Connor Harris', 'connor@example.com'),
    ('Evelyn Scott', 'evelyn@example.com'),
    ('Caleb Green', 'caleb@example.com'),
    ('Allison Baker', 'allison@example.com'),
    ('Isaac Gonzalez', 'isaac@example.com'),
    ('Makayla Nelson', 'makayla@example.com'),
    ('Justin Carter', 'justin@example.com'),
    ('Hannah Mitchell', 'hannah@example.com'),
    ('Elijah Perez', 'elijah@example.com'),
    ('Sophie Torres', 'sophie@example.com'),
    ('Landon Flores', 'landon@example.com'),
    ('Lily Morgan', 'lily@example.com'),
    ('Adrian Cooper', 'adrian@example.com'),
    ('Maya Reed', 'maya@example.com'),
    ('Ethan Price', 'ethan@example.com'),
    ('Ava Wright', 'ava@example.com'),
    ('Liam Hill', 'liam@example.com'),
    ('Olivia Ward', 'olivia@example.com'),
    ('Lucas Turner', 'lucas@example.com'),
    ('Mia Foster', 'mia@example.com'),
    ('Mason Cook', 'mason@example.com'),
    ('Charlotte Gray', 'charlotte@example.com'),
    ('Jacob Bell', 'jacob@example.com'),
    ('Amelia Murphy', 'amelia@example.com'),
    ('Logan Rivera', 'logan@example.com'),
    ('Harper Cooper', 'harper@example.com'),
    ('Elijah Ross', 'elijah@example.com'),
    ('Avery Reed', 'avery@example.com'),
    ('Evelyn Ward', 'evelyn@example.com'),
    ('Carter Price', 'carter@example.com'),
    ('Madison Wright', 'madison@example.com'),
    ('Noah Hill', 'noah@example.com'),
    ('Sophia Ward', 'sophia@example.com'),
    ('Alexander Turner', 'alexander@example.com');

INSERT INTO TaskAssignments (task_id, member_id, assigned_date, completed_date)
SELECT
    task_id,
    member_id,
    DATE_ADD(CURRENT_DATE(), INTERVAL FLOOR(RAND() * 60) DAY) AS assigned_date,
    CASE WHEN MOD(t.num, 7) = 0 THEN DATE_ADD(CURRENT_DATE(), INTERVAL FLOOR(RAND() * 60) DAY) ELSE NULL END AS completed_date
FROM
    (SELECT task_id, ROW_NUMBER() OVER (ORDER BY RAND()) AS num FROM Tasks LIMIT 200) AS t
CROSS JOIN
    (SELECT member_id FROM Members ORDER BY RAND() LIMIT 200) AS m;
